### ISSUE TITLE
在 Docker 容器中运行的守护进程无法正常使用虚拟化容器

### ISSUE THREAD

**Issue by YaoSiQian** [MCSManager/MCSManager#1037]
# 版本信息
|应用|版本|
|:-:|:-:|
|Web|9.9.0|
|Daemon|3.4.0|
## 安装方式
- 使用非官方包 [alisaqaq/mcsmanager-web:9.9.0](https://hub.docker.com/r/alisaqaq/mcsmanager-web)和[alisaqaq/mcsmanager-daemon:3.4.0](https://hub.docker.com/r/alisaqaq/mcsmanager-daemon)。
- **_（此处为主要出错原因）_** 将 Daemon 中的 `/opt/mcsmanager/daemon/data`挂载到宿主机的`/data/MCSM/data`，即不在同一目录。
# 主要问题
1. 假设一实例在 Daemon 容器中的工作目录为`/opt/mcsmanager/daemon/data/InstanceData/1145141919810`，那么其在宿主机的目录即为`/data/MCSM/data/1145141919810`。
2. 在使用 MCSM 的虚拟化容器功能时，会自动挂载工作目录到实例容器的`/workspace`。但是此时，实例容器挂载的“宿主机”目录则是 Daemon 中的`/opt/mcsmanager/daemon/data/InstanceData/1145141919810`，而不是真正宿主机的`/data/MCSM/data/1145141919810`。
3. 实例，启动！…则会导致类似于 #1002 的问题
# 如何解决
## 临时解决方案
- 设置宿主机关于`/opt/mcsmanager/daemon/data/InstanceData/`和`/data/MCSM/data/InstanceData/`的软链接
- 在启动实例时手动重新挂载目录到不同路径

## 更好的解决方案
- （较难）MCSM 的 Daemon 检测自己所处环境是否为容器。如果是，则检测 Docker 容器的挂载
- （较易）询问用户真正的宿主机的工作目录
- （较易）默认将工作目录的挂载显示在“额外挂载路径”中，并开放对其修改

**Comment by unitwk** [comment]
以后 MCSM 10.0 开发完毕后，我会推出一个官方的 Docker 镜像，可以解决你这些问题，此 issue 暂时保留。

**Comment by uv301** [comment]
v10中，在docker中安装的daemon容器端创建容器都会绑定失败：
2024-04-30 00:01:44 [04/30 00:01:44] [INFO] ----------------
2024-04-30 00:01:44 [04/30 00:01:44] [INFO] Session aGftLJcZrG2CUlQmAAAF: Request to start an instance
2024-04-30 00:01:44 [04/30 00:01:44] [INFO] UUID: [0f7e59e6f03e452abf921131779f5093] [NFWC]
2024-04-30 00:01:44 [04/30 00:01:44] [INFO] NAME: [MCSM-0f7e59]
2024-04-30 00:01:44 [04/30 00:01:44] [INFO] COMMAND: bash run.sh
2024-04-30 00:01:44 [04/30 00:01:44] [INFO] CWD: /opt/docker-mcsm/daemon/data/InstanceData/0f7e59e6f03e452abf921131779f5093/, WORKING_DIR: /workspace
2024-04-30 00:01:44 [04/30 00:01:44] [INFO] NET_MODE: bridgev6
2024-04-30 00:01:44 [04/30 00:01:44] [INFO] OPEN_PORT: {"25565/tcp":[{"HostPort":"25565"}]}
2024-04-30 00:01:44 [04/30 00:01:44] [INFO] BINDS: ["/opt/docker-mcsm/daemon/data/InstanceData/0f7e59e6f03e452abf921131779f5093/->/workspace"]
2024-04-30 00:01:44 [04/30 00:01:44] [INFO] NET_ALIASES: []
2024-04-30 00:01:44 [04/30 00:01:44] [INFO] MEM_LIMIT: -- MB
2024-04-30 00:01:44 [04/30 00:01:44] [INFO] TYPE: Docker Container
2024-04-30 00:01:44 [04/30 00:01:44] [INFO] ----------------
2024-04-30 00:01:44 [04/30 00:01:44] [ERROR] 实例0f7e59e6f03e452abf921131779f5093启动时错误:  Error: (HTTP code 400) unexpected - invalid mount config for type "bind": bind source path does not exist: /opt/docker-mcsm/daemon/data/InstanceData/0f7e59e6f03e452abf921131779f5093 
2024-04-30 00:01:44     at /opt/docker-mcsm/daemon/node_modules/docker-modem/lib/modem.js:301:17
2024-04-30 00:01:44     at getCause (/opt/docker-mcsm/daemon/node_modules/docker-modem/lib/modem.js:331:7)
2024-04-30 00:01:44     at Modem.buildPayload (/opt/docker-mcsm/daemon/node_modules/docker-modem/lib/modem.js:300:5)
2024-04-30 00:01:44     at IncomingMessage.<anonymous> (/opt/docker-mcsm/daemon/node_modules/docker-modem/lib/modem.js:275:14)
2024-04-30 00:01:44     at IncomingMessage.emit (node:events:529:35)
2024-04-30 00:01:44     at endReadableNT (node:internal/streams/readable:1400:12)
2024-04-30 00:01:44     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
2024-04-30 00:01:44   reason: undefined,
2024-04-30 00:01:44   statusCode: 400,
2024-04-30 00:01:44   json: {
2024-04-30 00:01:44     message: 'invalid mount config for type "bind": bind source path does not exist: /opt/docker-mcsm/daemon/data/InstanceData/0f7e59e6f03e452abf921131779f5093'
2024-04-30 00:01:44   }
2024-04-30 00:01:44 }

**Comment by csthenry** [comment]
> message: 'invalid mount config for type "bind": bind source path does not exist: /opt/docker-mcsm/daemon/data/InstanceData/0f7e59e6f03e452abf921131779f5093'

+1，解决了吗

**Comment by huangsijun17** [comment]
应该是路径问题。嵌套启动的Docker会去宿主机的实例目录挂载实例根目录到工作目录。而这个实例根目录是通过Docker里的MCSM设置的，是实例在daemon所在Docker里的路径。宿主机上这个路径没文件夹，就挂在不了目录，启动不起来。我是靠软连接解决的。

**Comment by csthenry** [comment]
> 应该是路径问题。嵌套启动的Docker会去宿主机的实例目录挂载实例根目录到工作目录。而这个实例根目录是通过Docker里的MCSM设置的，是实例在daemon所在Docker里的路径。宿主机上这个路径没文件夹，就挂在不了目录，启动不起来。我是靠软连接解决的。

我也是这样解决，不过后期应该还是需要有更简便的解决方案，否则官方的docker daemon镜像并不能够简单的通过面板进行容器化部署MC服务。

**Comment by csthenry** [comment]
> 应该是路径问题。嵌套启动的Docker会去宿主机的实例目录挂载实例根目录到工作目录。而这个实例根目录是通过Docker里的MCSM设置的，是实例在daemon所在Docker里的路径。宿主机上这个路径没文件夹，就挂在不了目录，启动不起来。我是靠软连接解决的。

有一个很简单的解决方案是，容器化部署时，让用户自行完成挂载卷，不再自动挂载工作目录。用户就可以自行设置正确的宿主机持久化目录。

**Comment by 0xingchen0** [comment]
反正我的的办法就是把主机的目录映射到daemon的目录，比如我就是 `-v /mnt/new_storage/mcsm/Servers:/mnt/new_storage/mcsm/Servers`，然后把工作目录改成`/mnt/new_storage/mcsm/Servers/XXX`，就完事了

**Comment by YaoSiQian** [comment]
是的，这是可行的办法，我也是这么干的
&nbsp;


??qianqian
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2024年8月17日(星期六) 下午2:34
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [MCSManager/MCSManager] 在 Docker 容器中运行的守护进程无法正常使用虚拟化容器 (Issue #1037)














 
反正我的的办法就是把主机的目录映射到daemon的目录，比如我就是 -v /mnt/new_storage/mcsm/Servers:/mnt/new_storage/mcsm/Servers，然后把工作目录改成/mnt/new_storage/mcsm/Servers/XXX，就完事了

**Comment by chivehao** [comment]
这个问题貌似，只需要把实例配置的工作目录，修改为实际的宿主机目录就行了

![Image](https://github.com/user-attachments/assets/e781e701-9599-4cb1-bb28-7d1a2af95090)
