### ISSUE TITLE
Docker for Windows 

### ISSUE THREAD

**Issue by redhogoftime** [MCSManager/MCSManager#1071]
**MCSManager Version** 9.9.0

**System Info/Version** WINDOWS 10

**Node Version**
14
**Step**
[MCSMANAGER] [Error] (HTTP code 400) unexpected - failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "bedrockserver.exe": executable file not found in $PATH: unknown 

im at windows 10 and i am setting up the mcsmanager to use the docker linux i have installed the docker for windows but when i try to start my server above is the problem is there any way to fix this? i do not know much from linux thats is why im using windows. 
![github 1](https://github.com/MCSManager/MCSManager/assets/104266848/acafdaef-daf6-46d8-809d-75acd73a0342)
![github 2](https://github.com/MCSManager/MCSManager/assets/104266848/8e57b3ab-08b7-4611-8a65-6da507fe7207)

**Comment by redhogoftime** [comment]
i am currently using jdk17 for the container configuration

**Comment by huangsijun17** [comment]
1. You seem to have a problem with the $PATH variable. Run a SHELL and enter `echo $PATH` to see the return value.
2. Docker Desktop under Windows is a Linux Docker. Please do not use Docker Desktop to run Windows programs without special adaptation.
3. Docker does not use the host's Java, please use the JDK image.

**Comment by redhogoftime** [comment]
> 1. You seem to have a problem with the $PATH variable. Run a SHELL and enter `echo $PATH` to see the return value.
> 
>     2. Docker Desktop under Windows is a Linux Docker. Please do not use Docker Desktop to run Windows programs without special adaptation.
> 
>     3. Docker does not use the host's Java, please use the JDK image.

how can i run the shell? does windows have shell? is it the power shell?

sorry i have a little knowledge about programming i am using the jdk image 16.

i think i might have a mistake here 
do i have to configure the docker desktop? because i only did installed it and then i get back to the mcs manager web and installed the jdk image and that is it the problem occurs like in photo i have attached

**Comment by huangsijun17** [comment]
The only Docker for Windows is Docker Desktop, which runs over WSL2. If you want to run Docker on Windows, you can only run Docker Desktop.
If you are not using Docker, you can set the startup command to `CMD` to run SHELL.

**Comment by redhogoftime** [comment]
i have the docker desktop 
now if i could ask if theres something i have to do on the docker desktop  to be able to have connections with my daemon because i did just installed the docker desktop and did nothing but installed the images in the mcsmanager

**Comment by redhogoftime** [comment]
sorry if you could really help me with this ireally appreciate i really dont know much about linux commands please help me how can i set up my mcs daemon to use the linux docker (docker desktop)

**Comment by Dokman** [comment]
```
[07/05 11:41:35] [ERROR] Error occurred while starting instance 3b239e16d0394a50bc4ba5d07284f4ae:   Error: Image download error, please make sure the image name is correct, or manually pull the required image using docker pull via the node management terminal, error:
connect ENOENT /var/run/docker.sock
    at DockerPullCommand.exec (webpack://mcsmanager-daemon/src/entity/commands/docker/docker_pull.ts:70:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Instance.forceExec (webpack://mcsmanager-daemon/src/entity/instance/instance.ts:240:12)
    at async DockerStartCommand.createProcess (webpack://mcsmanager-daemon/src/entity/commands/docker/docker_start.ts:22:7)
    at async DockerStartCommand.exec (webpack://mcsmanager-daemon/src/entity/commands/start.ts:44:14)
    at async PresetCommandManager.execPreset (webpack://mcsmanager-daemon/src/entity/instance/preset.ts:24:12)
    at async Instance.execPreset (webpack://mcsmanager-daemon/src/entity/instance/instance.ts:366:14)
    at async RouterApp.<anonymous> (webpack://mcsmanager-daemon/src/routers/Instance_router.ts:224:7)
[07/05 11:41:35] [WARN] Session Ai0rYYf4dJjYehpnAAAB(::1)/instance/open  encountered an exception when responding:
 {
  instanceUuid: '3b239e16d0394a50bc4ba5d07284f4ae',
  err: 'Image download error, please make sure the image name is correct, or manually pull the required image using docker pull via the node management terminal, error:\n' +
    'connect ENOENT /var/run/docker.sock'
}
```

I'm getting this error
