### ISSUE TITLE
[Bug Report] 启动报错

### ISSUE THREAD

**Issue by lamya3** [MCSManager/MCSManager#1218]
### Platform

Windows Server 2022 Datacenter 21H2, OpenJDK 16.0.2, SpigotMC(1.16.5)

### Panel Version

10.0.4

### Daemon Version (Optional)

4.1.0

### Recurrence Probability

100%

### Bug Description

```
Loading libraries, please wait...
2024-05-16 11:51:23,215 main ERROR Unable to inject fields into builder class for plugin type class org.apache.logging.log4j.core.appender.ConsoleAppender, element
Console. java.nio.charset.UnsupportedCharsetException: cp65001
        at java.base/java.nio.charset.Charset.forName(Charset.java:526)
        at org.apache.logging.log4j.util.PropertiesUtil.getCharsetProperty(PropertiesUtil.java:146)
        at org.apache.logging.log4j.util.PropertiesUtil.getCharsetProperty(PropertiesUtil.java:134)
        at org.apache.logging.log4j.core.appender.ConsoleAppender$Target.getCharset(ConsoleAppender.java:85)
        at org.apache.logging.log4j.core.appender.ConsoleAppender$Target$1.getDefaultCharset(ConsoleAppender.java:71)
        at org.apache.logging.log4j.core.appender.ConsoleAppender$Builder.build(ConsoleAppender.java:218)
        at org.apache.logging.log4j.core.appender.ConsoleAppender$Builder.build(ConsoleAppender.java:185)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:952)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:892)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:884)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:508)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:232)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:244)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:545)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:617)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:634)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:229)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:152)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:551)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:537)
        at net.minecraft.server.v1_16_R3.Main.<clinit>(Main.java:65)
        at org.bukkit.craftbukkit.Main.main(Main.java:202)

2024-05-16 11:51:23,235 main ERROR Unable to invoke factory method in class class org.apache.logging.log4j.core.appender.ConsoleAppender for element Console. java.l
ang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.ConsoleAppender
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.findFactoryMethod(PluginBuilder.java:224)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:130)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:952)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:892)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:884)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:508)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:232)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:244)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:545)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:617)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:634)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:229)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:152)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:551)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:537)
        at net.minecraft.server.v1_16_R3.Main.<clinit>(Main.java:65)
        at org.bukkit.craftbukkit.Main.main(Main.java:202)

2024-05-16 11:51:23,278 main ERROR Null object returned for Console in Appenders.
2024-05-16 11:51:23,297 main ERROR Unable to locate appender "SysOut" for logger config "root"
```

#### 已排除，确定是非服务端程序的问题。

**Comment by unitwk** [comment]
尝试将终端的编码从 GBK 改成 UTF-8 ，并且尝试在启动命令中加入 `-Dfile.encoding=utf-8` 这类的启动参数来尝试。

**Comment by lamya3** [comment]
> 尝试将终端的编码从 GBK 改成 UTF-8 ，并且尝试在启动命令中加入 `-Dfile.encoding=utf-8` 这类的启动参数来尝试。

启动参数为:
```
java -server -javaagent:authlib-injector.jar=https://littleskin.cn/api/yggdrasil -Xms10G -Xmx10G -Dfile.encoding=utf-8 -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -jar server.jar nogui
```
#### 在加入`-Dfile.encoding=utf-8`启动参数后问题有改善吗？
##### 在加入和去除`-Dfile.encoding=utf-8`参数后均报相同错误。
#### 在更改终端编码为UTF-8后问题有改善吗？
##### 默认即为UTF-8，曾改为GBK或者其他GB字体均报同样的错误(甚至终端乱码)

**Comment by huangsijun17** [comment]
确认一下，没有使用Docker Dsektop吧。

**Comment by huangsijun17** [comment]
错误是log4j写出日志相关的，实例路径等有包含中文之类的吗？
试试看这个参数：
`-Dsun.jnu.encoding=UTF8 -Dfile.encoding=UTF8 -Ds=0`

**Comment by lamya3** [comment]
> 错误是log4j写出日志相关的，实例路径等有包含中文之类的吗？ 试试看这个参数： `-Dsun.jnu.encoding=UTF8 -Dsun.stdout.encoding=UTF-8 -Dfile.encoding=UTF8 -Ds=0`

实例路径没有中文，使用了`-Dsun.jnu.encoding=UTF8 -Dsun.stdout.encoding=UTF-8 -Dfile.encoding=UTF8 -Ds=0`问题已经解决，此错误会发生在面板启动阶段，不会发生在bat启动中

**Comment by lamya3** [comment]
> 尝试将终端的编码从 GBK 改成 UTF-8 ，并且尝试在启动命令中加入 `-Dfile.encoding=utf-8` 这类的启动参数来尝试。

改成GBK不再报错误，但是控制台里面的中文会乱码

**Comment by lamya3** [comment]
> 确认一下，没有使用Docker Dsektop吧。

没有

**Comment by Bluemangoo** [comment]
> > 尝试将终端的编码从 GBK 改成 UTF-8 ，并且尝试在启动命令中加入 `-Dfile.encoding=utf-8` 这类的启动参数来尝试。
> 
> 改成GBK不再报错误，但是控制台里面的中文会乱码

实例设置里面改下输入输出编码。

**Comment by huangsijun17** [comment]
> > 错误是log4j写出日志相关的，实例路径等有包含中文之类的吗？ 试试看这个参数： `-Dsun.jnu.encoding=UTF8 -Dsun.stdout.encoding=UTF-8 -Dfile.encoding=UTF8 -Ds=0`
> 
> 实例路径没有中文，使用了`-Dsun.jnu.encoding=UTF8 -Dsun.stdout.encoding=UTF-8 -Dfile.encoding=UTF8 -Ds=0`问题已经解决，此错误会发生在面板启动阶段，不会发生在bat启动中

我怀疑，可能和传入的路径参数的编码格式有关。
