### ISSUE TITLE
[Bug Report] 资源网站的SSL证书过期

### ISSUE THREAD

**Issue by null0034** [MCSManager/MCSManager#1239]
### Platform

Ubuntu22.04.4

### Panel Version

10.1

### Recurrence Probability

100%

### Bug Description

目前根据错误日志来看，应该是 https://url.alww.top 网址的SSL证书过期了，目前无法正常下载资源文件，以下为主要错误信息：
```txt
[2K1Panel-mcsmanager-daemon-VPBQ  |     xsrfCookieName: 'XSRF-TOKEN',
[2K1Panel-mcsmanager-daemon-VPBQ  |     xsrfHeaderName: 'X-XSRF-TOKEN',
[2K1Panel-mcsmanager-daemon-VPBQ  |     maxContentLength: -1,
[2K1Panel-mcsmanager-daemon-VPBQ  |     maxBodyLength: -1,
[2K1Panel-mcsmanager-daemon-VPBQ  |     env: { FormData: [Function], Blob: null },
[2K1Panel-mcsmanager-daemon-VPBQ  |     validateStatus: [Function: validateStatus],
[2K1Panel-mcsmanager-daemon-VPBQ  |     headers: AxiosHeaders {
[2K1Panel-mcsmanager-daemon-VPBQ  |       'User-Agent': 'axios/1.1.3',
[2K1Panel-mcsmanager-daemon-VPBQ  |       'Accept-Encoding': 'gzip, deflate, br',
[2K1Panel-mcsmanager-daemon-VPBQ  |       [Symbol(defaults)]: [Object]
[2K1Panel-mcsmanager-daemon-VPBQ  |     },
[2K1Panel-mcsmanager-daemon-VPBQ  |     url: 'https://url.alww.top/mcsm/arclight1.19.2',
[2K1Panel-mcsmanager-daemon-VPBQ  |     responseType: 'stream',
[2K1Panel-mcsmanager-daemon-VPBQ  |     method: 'get',
[2K1Panel-mcsmanager-daemon-VPBQ  |     data: undefined
[2K1Panel-mcsmanager-daemon-VPBQ  |   },
[2K1Panel-mcsmanager-daemon-VPBQ  |   request: <ref *1> Writable {
[2K1Panel-mcsmanager-daemon-VPBQ  |     _writableState: WritableState {
[2K1Panel-mcsmanager-daemon-VPBQ  |       objectMode: false,
[2K1Panel-mcsmanager-daemon-VPBQ  |       highWaterMark: 16384,
[2K1Panel-mcsmanager-daemon-VPBQ  |       finalCalled: false,
[2K1Panel-mcsmanager-daemon-VPBQ  |       needDrain: false,
[2K1Panel-mcsmanager-daemon-VPBQ  |       ending: false,
[2K1Panel-mcsmanager-daemon-VPBQ  |       ended: false,
[2K1Panel-mcsmanager-daemon-VPBQ  |       finished: false,
[2K1Panel-mcsmanager-daemon-VPBQ  |       destroyed: false,
[2K1Panel-mcsmanager-daemon-VPBQ  |       decodeStrings: true,
[2K1Panel-mcsmanager-daemon-VPBQ  |       defaultEncoding: 'utf8',
[2K1Panel-mcsmanager-daemon-VPBQ  |       length: 0,
[2K1Panel-mcsmanager-daemon-VPBQ  |       writing: false,
[2K1Panel-mcsmanager-daemon-VPBQ  |       corked: 0,
[2K1Panel-mcsmanager-daemon-VPBQ  |       sync: true,
[2K1Panel-mcsmanager-daemon-VPBQ  |       bufferProcessing: false,
[2K1Panel-mcsmanager-daemon-VPBQ  |       onwrite: [Function: bound onwrite],
[2K1Panel-mcsmanager-daemon-VPBQ  |       writecb: null,
[2K1Panel-mcsmanager-daemon-VPBQ  |       writelen: 0,
[2K1Panel-mcsmanager-daemon-VPBQ  |       afterWriteTickInfo: null,
[2K1Panel-mcsmanager-daemon-VPBQ  |       buffered: [],
[2K1Panel-mcsmanager-daemon-VPBQ  |       bufferedIndex: 0,
[2K1Panel-mcsmanager-daemon-VPBQ  |       allBuffers: true,
[2K1Panel-mcsmanager-daemon-VPBQ  |       allNoop: true,
[2K1Panel-mcsmanager-daemon-VPBQ  |       pendingcb: 0,
[2K1Panel-mcsmanager-daemon-VPBQ  |       prefinished: false,
[2K1Panel-mcsmanager-daemon-VPBQ  |       errorEmitted: false,
[2K1Panel-mcsmanager-daemon-VPBQ  |       emitClose: true,
[2K1Panel-mcsmanager-daemon-VPBQ  |       autoDestroy: true,
[2K1Panel-mcsmanager-daemon-VPBQ  |       errored: null,
[2K1Panel-mcsmanager-daemon-VPBQ  |       closed: false
[2K1Panel-mcsmanager-daemon-VPBQ  |     },
[2K1Panel-mcsmanager-daemon-VPBQ  |     _events: [Object: null prototype] {
[2K1Panel-mcsmanager-daemon-VPBQ  |       response: [Function: handleResponse],
[2K1Panel-mcsmanager-daemon-VPBQ  |       error: [Function: handleRequestError],
[2K1Panel-mcsmanager-daemon-VPBQ  |       socket: [Function: handleRequestSocket]
[2K1Panel-mcsmanager-daemon-VPBQ  |     },
[2K1Panel-mcsmanager-daemon-VPBQ  |     _eventsCount: 3,
[2K1Panel-mcsmanager-daemon-VPBQ  |     _maxListeners: undefined,
[2K1Panel-mcsmanager-daemon-VPBQ  |     _options: {
[2K1Panel-mcsmanager-daemon-VPBQ  |       maxRedirects: 21,
[2K1Panel-mcsmanager-daemon-VPBQ  |       maxBodyLength: Infinity,
[2K1Panel-mcsmanager-daemon-VPBQ  |       protocol: 'https:',
[2K1Panel-mcsmanager-daemon-VPBQ  |       path: '/mcsm/arclight1.19.2',
[2K1Panel-mcsmanager-daemon-VPBQ  |       method: 'GET',
[2K1Panel-mcsmanager-daemon-VPBQ  |       headers: [Object: null prototype],
[2K1Panel-mcsmanager-daemon-VPBQ  |       agents: [Object],
[2K1Panel-mcsmanager-daemon-VPBQ  |       auth: undefined,
[2K1Panel-mcsmanager-daemon-VPBQ  |       beforeRedirect: [Function: dispatchBeforeRedirect],
[2K1Panel-mcsmanager-daemon-VPBQ  |       beforeRedirects: [Object],
[2K1Panel-mcsmanager-daemon-VPBQ  |       hostname: 'url.alww.top',
[2K1Panel-mcsmanager-daemon-VPBQ  |       port: '',
[2K1Panel-mcsmanager-daemon-VPBQ  |       agent: undefined,
[2K1Panel-mcsmanager-daemon-VPBQ  |       nativeProtocols: [Object],
[2K1Panel-mcsmanager-daemon-VPBQ  |       pathname: '/mcsm/arclight1.19.2'
[2K1Panel-mcsmanager-daemon-VPBQ  |     },
[2K1Panel-mcsmanager-daemon-VPBQ  |     _ended: true,
[2K1Panel-mcsmanager-daemon-VPBQ  |     _ending: true,
[2K1Panel-mcsmanager-daemon-VPBQ  |     _redirectCount: 0,
[2K1Panel-mcsmanager-daemon-VPBQ  |     _redirects: [],
[2K1Panel-mcsmanager-daemon-VPBQ  |     _requestBodyLength: 0,
[2K1Panel-mcsmanager-daemon-VPBQ  |     _requestBodyBuffers: [],
[2K1Panel-mcsmanager-daemon-VPBQ  |     _onNativeResponse: [Function (anonymous)],
[2K1Panel-mcsmanager-daemon-VPBQ  |     _currentRequest: ClientRequest {
[2K1Panel-mcsmanager-daemon-VPBQ  |       _events: [Object: null prototype],
[2K1Panel-mcsmanager-daemon-VPBQ  |       _eventsCount: 7,
[2K1Panel-mcsmanager-daemon-VPBQ  |       _maxListeners: undefined,
[2K1Panel-mcsmanager-daemon-VPBQ  |       outputData: [],
[2K1Panel-mcsmanager-daemon-VPBQ  |       outputSize: 0,
[2K1Panel-mcsmanager-daemon-VPBQ  |       writable: true,
[2K1Panel-mcsmanager-daemon-VPBQ  |       destroyed: false,
[2K1Panel-mcsmanager-daemon-VPBQ  |       _last: true,
[2K1Panel-mcsmanager-daemon-VPBQ  |       chunkedEncoding: false,
[2K1Panel-mcsmanager-daemon-VPBQ  |       shouldKeepAlive: false,
[2K1Panel-mcsmanager-daemon-VPBQ  |       _defaultKeepAlive: true,
[2K1Panel-mcsmanager-daemon-VPBQ  |       useChunkedEncodingByDefault: false,
[2K1Panel-mcsmanager-daemon-VPBQ  |       sendDate: false,
[2K1Panel-mcsmanager-daemon-VPBQ  |       _removedConnection: false,
[2K1Panel-mcsmanager-daemon-VPBQ  |       _removedContLen: false,
[2K1Panel-mcsmanager-daemon-VPBQ  |       _removedTE: false,
[2K1Panel-mcsmanager-daemon-VPBQ  |       _contentLength: 0,
[2K1Panel-mcsmanager-daemon-VPBQ  |       _hasBody: true,
[2K1Panel-mcsmanager-daemon-VPBQ  |       _trailer: '',
[2K1Panel-mcsmanager-daemon-VPBQ  |       finished: true,
[2K1Panel-mcsmanager-daemon-VPBQ  |       _headerSent: true,
[2K1Panel-mcsmanager-daemon-VPBQ  |       socket: [TLSSocket],
[2K1Panel-mcsmanager-daemon-VPBQ  |       _header: 'GET /mcsm/arclight1.19.2 HTTP/1.1\r\n' +
[2K1Panel-mcsmanager-daemon-VPBQ  |         'Accept: application/json, text/plain, */*\r\n' +
[2K1Panel-mcsmanager-daemon-VPBQ  |         'User-Agent: axios/1.1.3\r\n' +
[2K1Panel-mcsmanager-daemon-VPBQ  |         'Accept-Encoding: gzip, deflate, br\r\n' +
[2K1Panel-mcsmanager-daemon-VPBQ  |         'Host: url.alww.top\r\n' +
[2K1Panel-mcsmanager-daemon-VPBQ  |         'Connection: close\r\n' +
[2K1Panel-mcsmanager-daemon-VPBQ  |         '\r\n',
[2K1Panel-mcsmanager-daemon-VPBQ  |       _keepAliveTimeout: 0,
[2K1Panel-mcsmanager-daemon-VPBQ  |       _onPendingData: [Function: noopPendingOutput],
[2K1Panel-mcsmanager-daemon-VPBQ  |       agent: [Agent],
[2K1Panel-mcsmanager-daemon-VPBQ  |       socketPath: undefined,
[2K1Panel-mcsmanager-daemon-VPBQ  |       method: 'GET',
[2K1Panel-mcsmanager-daemon-VPBQ  |       maxHeaderSize: undefined,
[2K1Panel-mcsmanager-daemon-VPBQ  |       insecureHTTPParser: undefined,
[2K1Panel-mcsmanager-daemon-VPBQ  |       path: '/mcsm/arclight1.19.2',
[2K1Panel-mcsmanager-daemon-VPBQ  |       _ended: false,
[2K1Panel-mcsmanager-daemon-VPBQ  |       res: null,
[2K1Panel-mcsmanager-daemon-VPBQ  |       aborted: false,
[2K1Panel-mcsmanager-daemon-VPBQ  |       timeoutCb: null,
[2K1Panel-mcsmanager-daemon-VPBQ  |       upgradeOrConnect: false,
[2K1Panel-mcsmanager-daemon-VPBQ  |       parser: null,
[2K1Panel-mcsmanager-daemon-VPBQ  |       maxHeadersCount: null,
[2K1Panel-mcsmanager-daemon-VPBQ  |       reusedSocket: false,
[2K1Panel-mcsmanager-daemon-VPBQ  |       host: 'url.alww.top',
[2K1Panel-mcsmanager-daemon-VPBQ  |       protocol: 'https:',
[2K1Panel-mcsmanager-daemon-VPBQ  |       _redirectable: [Circular *1],
[2K1Panel-mcsmanager-daemon-VPBQ  |       [Symbol(kCapture)]: false,
[2K1Panel-mcsmanager-daemon-VPBQ  |       [Symbol(kNeedDrain)]: false,
[2K1Panel-mcsmanager-daemon-VPBQ  |       [Symbol(corked)]: 0,
[2K1Panel-mcsmanager-daemon-VPBQ  |       [Symbol(kOutHeaders)]: [Object: null prototype]
[2K1Panel-mcsmanager-daemon-VPBQ  |     },
[2K1Panel-mcsmanager-daemon-VPBQ  |     _currentUrl: 'https://url.alww.top/mcsm/arclight1.19.2',
[2K1Panel-mcsmanager-daemon-VPBQ  |     [Symbol(kCapture)]: false
[2K1Panel-mcsmanager-daemon-VPBQ  |   },
[2K1Panel-mcsmanager-daemon-VPBQ  |   cause: Error: certificate has expired
[2K1Panel-mcsmanager-daemon-VPBQ  |       at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)
[2K1Panel-mcsmanager-daemon-VPBQ  |       at TLSSocket.emit (events.js:400:28)
[2K1Panel-mcsmanager-daemon-VPBQ  |       at TLSSocket._finishInit (_tls_wrap.js:937:8)
[2K1Panel-mcsmanager-daemon-VPBQ  |       at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12) {
[2K1Panel-mcsmanager-daemon-VPBQ  |     code: 'CERT_HAS_EXPIRED'
[2K1Panel-mcsmanager-daemon-VPBQ  |   }
```

**Comment by alongw** [comment]
将模板地址更换为 `https://script.mcsmanager.com/templates.json`

**Comment by null0034** [comment]
> 将模板地址更换为 `https://script.mcsmanager.com/templates.json`

我要在那里修改呢 @alongw

**Comment by null0034** [comment]
> 将模板地址更换为 `https://script.mcsmanager.com/templates.json`

我使用的docker

**Comment by alongw** [comment]
> > 将模板地址更换为 `https://script.mcsmanager.com/templates.json`
> 
> 我要在那里修改呢 @alongw

![image](https://github.com/MCSManager/MCSManager/assets/64565408/b086bb49-3fb5-497f-a8e9-4c7182b9e9ee)
修改此地址

**Comment by null0034** [comment]
> > > 将模板地址更换为 `https://script.mcsmanager.com/templates.json`
> > 
> > 
> > 我要在那里修改呢 @alongw
> 
> ![image](https://private-user-images.githubusercontent.com/64565408/334263868-b086bb49-3fb5-497f-a8e9-4c7182b9e9ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4Njk0MzEsIm5iZiI6MTcxNjg2OTEzMSwicGF0aCI6Ii82NDU2NTQwOC8zMzQyNjM4NjgtYjA4NmJiNDktM2ZiNS00OTdmLWE4ZTktNGM3MTgyYjllOWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDA0MDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwNWJmYzI0NDg2ZmIyMTRmNTRiMzkzZmU5MTk2OGQwNTQ4NTc4ZGFlZDFjOWE3MjZjYTVlMDRiMzNiOTU0NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b8o_px6xNSAPDMegI4CJmBnWFQymRIUoXGnKL6rMkn4) 修改此地址

好的我试试，感谢
