### ISSUE TITLE
[Bug Report] 服务器重启失败 但是进程已运行

### ISSUE THREAD

**Issue by Chaostarts** [MCSManager/MCSManager#1322]
### Platform

Windows Server2019

### Panel Version

10.2.1

### Daemon Version (Optional)

4.4.1

### Recurrence Probability

80%

### Bug Description

我在mcsm使用了计划任务 定时重启 但是每次都会显示启动中 点进去会提示
`[04:00:05 INFO]: Thank you and goodbye
[INFO] 检测到服务器已停止，正在重启实例...
[INFO] 检测到服务器已停止，正在重启实例...
[Operation Error] 重启实例状态错误，实例已被启动过，上次状态的重启计划取消
[ERROR] 检测到进程启动失败，其可能的原因是：
1. 实例启动命令编写错误，请前往实例设置界面检查启动命令与参数。
2. 系统主机环境不正确或缺少环境，比如缺少 Java 环境等。

启动命令：
start.bat 

请将此信息报告给管理员，技术人员或自行排查故障。
[Operation Error] 实例启动失败，请检查启动命令，主机环境和配置文件等`
`[08/05 04:00:06] [INFO] 会话 Unknown: 请求开启实例，模式为仿真终端
[08/05 04:00:06] [INFO] ----------------
[08/05 04:00:06] [INFO] 会话 Unknown: 请求开启实例.
[08/05 04:00:06] [INFO] 实例标识符: [47fcab925f534d2bad0462063f080aa1]
[08/05 04:00:06] [INFO] 启动命令: start.bat
[08/05 04:00:06] [INFO] PTY 路径: D:\MCSM\daemon\lib\pty_win32_x64.exe
[08/05 04:00:06] [INFO] PTY 参数: -size 164,40 -coder UTF-8 -dir E:\ServerCore\[3]主大厅#1\Waterfall and Login\[1]Waterfall -fifo \\.\pipe\mcsmanager-47fcab925f534d2bad0462063f080aa1 -cmd ["start.bat "]
[08/05 04:00:06] [INFO] 工作目录: E:\ServerCore\[3]主大厅#1\Waterfall and Login\[1]Waterfall
[08/05 04:00:06] [INFO] ----------------
[08/05 04:00:09] [ERROR] Error: UnhandledRejection: Error: 重启实例状态错误，实例已被启动过，上次状态的重启计划取消
    at Timeout.<anonymous> (D:\MCSM\daemon\app.js:1619:31)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) Promise {
  <rejected> Error: 重启实例状态错误，实例已被启动过，上次状态的重启计划取消
      at Timeout.<anonymous> (D:\MCSM\daemon\app.js:1619:31)
      at listOnTimeout (node:internal/timers:573:17)
      at process.processTimers (node:internal/timers:514:7)
}
[08/05 04:00:11] [ERROR] Init Pipe Err: \\.\pipe\mcsmanager-47fcab925f534d2bad0462063f080aa1, Error: ENOENT: no such file or directory, open '\\.\pipe\mcsmanager-47fcab925f534d2bad0462063f080aa1'
[08/05 04:00:11] [INFO] pty.exe response: {"pid":0}
[08/05 04:00:11] [ERROR] Error: UnhandledRejection: StartupError: 实例启动失败，请检查启动命令，主机环境和配置文件等
    at PtyStartCommand.exec (D:\MCSM\daemon\app.js:2224:19)
    at async PresetCommandManager.execPreset (D:\MCSM\daemon\app.js:3180:16)
    at async Instance.execPreset (D:\MCSM\daemon\app.js:3073:20)
    at async Timeout.<anonymous> (D:\MCSM\daemon\app.js:1627:25) Promise {
  <rejected> StartupError: 实例启动失败，请检查启动命令，主机环境和配置文件等
      at PtyStartCommand.exec (D:\MCSM\daemon\app.js:2224:19)
      at async PresetCommandManager.execPreset (D:\MCSM\daemon\app.js:3180:16)
      at async Instance.execPreset (D:\MCSM\daemon\app.js:3073:20)
      at async Timeout.<anonymous> (D:\MCSM\daemon\app.js:1627:25)
}`

其实进程已启动 能否修复这个问题 这个问题非常影响使用体验 甚至开启daemon还会自启动不成功 还要进游戏对bc /end 再启动bc才有可能成功

**Comment by huangsijun17** [comment]
请提供start.bat内容，另外，不建议用第三方bat。

**Comment by Chaostarts** [comment]
> 请提供start.bat内容，另外，不建议用第三方bat。

`@echo OFF
chcp 65001
"D:\Java\zulu21\bin\java.exe" -Xms1G -Xmx1G -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=10809   -Dfile.encoding=utf-8 -Duser.language=zh -Duser.country=CN -jar waterfall-1.21-579.jar nogui
exit`

**Comment by Chaostarts** [comment]
不使用bat也会这样 能解决吗

**Comment by huangsijun17** [comment]
看了一下bat，没用start命令之类，看上去没什么大问题。

**Comment by yumao233** [comment]
10.8.X 已修复，如果还有存在类似问题，可以继续新建 issue 反馈。
