### ISSUE TITLE
[Bug Report] 使用使用容器化运行实例出现读取不到文件的问题

### ISSUE THREAD

**Issue by Deemo119** [MCSManager/MCSManager#1429]
### Platform

ubuntu22

### Panel Version

10.4.0

### Daemon Version (Optional)

4.5.0

### Recurrence Probability

100%

### Bug Description

使用容器化启动后报错日志为
You are on platform: "Linux" arch: "x86_64"
Logging to /workspace/tModLoader-Logs/Launch.log
Fixing Environment Issues
Success!
Verifying .NET....
This may take a few moments.
Parsing .NET version requirements from runtimeconfig.json
Success! dotnet_version=8.0.0
./LaunchUtils/ScriptCaller.sh: line 65: file: command not found
Checking for old .NET versions to remove from folder
Cleanup Complete
Checking dotnet install...
Dotnet should be present in "/workspace/dotnet"
Attempting Launch...
Launched Using Local Dotnet. Launch command: "/workspace/dotnet/dotnet" tModLoader.dll "-server -lang 7 -config serverconfig.txt"
=]0;Terraria Server v1.4.4.9 - tModLoader v2024.6.3.1查找模组……
初始化……
自动加载中：tModLoader v2024.6.3.1
增容中……
特殊调整内容：tModLoader v2024.6.3.1
完成最后步骤：tModLoader v2024.6.3.1
添加合成配方……
泰拉瑞亚服务器v1.4.4.9

Could not find a part of the path '/opt/mcsmanager/daemon/data/InstanceData/tmod端口8888/Terraria/tModLoader/Worlds/hututu.wld'. （请参阅 server.log 以获取完整调用堆栈）
Could not find a part of the path '/opt/mcsmanager/daemon/data/InstanceData/tmod端口8888/Terraria/tModLoader/Worlds/hututu.wld'. （请参阅 server.log 以获取完整调用堆栈）
加载失败！找不到备份。
Running one update...
minValue must be less than maxValue (Parameter 'minValue') （请参阅 server.log 以获取完整调用堆栈）

System.IO.DirectoryNotFoundException: Could not find a part of the path '/opt/mcsmanager/daemon/data/InstanceData/tmod端口8888/Terraria/tModLoader/Worlds/hututu.wld'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.ReadAllBytes(String path)
   at Terraria.Utilities.FileUtilities.ReadAllBytes(String path, Boolean cloud) in tModLoader\Terraria\Utilities\FileUtilities.cs:line 95
   at Terraria.IO.WorldFile.LoadWorld(Boolean loadFromCloud) in tModLoader\Terraria\IO\WorldFile.cs:line 481
容器化设置为
![屏幕截图 2024-11-09 164629](https://github.com/user-attachments/assets/13425f22-2ede-410a-9043-32fccd298967)

补充：可以使用容器化得到新的地图并开始游玩，但是无法加载模组和地图等文件

**Comment by Deemo119** [comment]
刚刚自己发现了，需要将配置文件使用容器内目录，问题已经解决
