### ISSUE TITLE
Docker容器创建模式问题

### ISSUE THREAD

**Issue by koiNoCirculation** [MCSManager/MCSManager#889]
**MCSManager Version**
master
**System Info/Version**

**Node Version**

**Step**
<img width="1338" alt="image" src="https://github.com/MCSManager/MCSManager/assets/57739338/5fa1ad52-6b2f-4933-969b-e85c3694212f">

docker容器模式下，由于WORKDIR和CMD两个指令的存在，启动命令和工作目录两项不应当成为必填项，填了反而报错。
并且docker容器模式报错非常的模糊，只会讲“容器退出”，没有原因，甚至docker ps -a也找不到。
希望能够改进（我不会nodejs）。

**Comment by koiNoCirculation** [comment]
docker配置如下：
<img width="1655" alt="image" src="https://github.com/MCSManager/MCSManager/assets/57739338/012efe60-6cc6-44c7-95b6-014b1de53306">

一两分钟前启动，提示退出：
[MCSMANAGER] [ERROR] Instance exited short after started, might be due to a wrong start command or configuration.
但docker ps -a找不到任何参考信息
<img width="943" alt="image" src="https://github.com/MCSManager/MCSManager/assets/57739338/a275314b-b712-4856-93e5-0fdcd484fcca">
使用： 
docker run -it -v /home/mcsm-daemon/gtnh-moyu/world:/workspace/world -v /home/mcsm-daemon/gtnh-moyu/backups:/workspace/backups -v /home/mcsm-daemon/gtnh-moyu/visualprospecting:/workspace/visualprospecting -p 25565:25565 gtnh:2.3.0-sihuo
 是可以直接启动的
<img width="1356" alt="image" src="https://github.com/MCSManager/MCSManager/assets/57739338/871a2033-767c-4bff-aeb1-01b487ab9a48">

**Comment by koiNoCirculation** [comment]
```
root@ubuntu:/home/mcsm-daemon# docker run -it -v /home/mcsm-daemon/gtnh-moyu/world:/workspace/world -v /home/mcsm-daemon/gtnh-moyu/backups:/workspace/backups -v /home/mcsm-daemon/gtnh-moyu/visualprospecting:/workspace/visualprospecting -p 25565:25565 gtnh:2.3.0-sihuo
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=warn; support was removed in 17.0
[06:03:08] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by cpw.mods.fml.common.launcher.FMLTweaker (file:/workspace/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar)
WARNING: Please consider reporting this to the maintainers of cpw.mods.fml.common.launcher.FMLTweaker
WARNING: System::setSecurityManager will be removed in a future release
[06:03:08] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[06:03:08] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
[06:03:08] [main/INFO]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[06:03:08] [main/INFO]: Java is OpenJDK 64-Bit Server VM, version 19, running on Linux:amd64:5.15.0-71-generic, installed at /usr/local/openjdk-19
[06:03:08] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[06:03:08] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[06:03:08] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[06:03:08] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[06:03:08] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[06:03:08] [main/INFO]: Injecting coremod FMLCorePlugin {cpw.mods.fml.relauncher.FMLCorePlugin} class transformers
[06:03:09] [main/INFO]: [cpw.mods.fml.common.TracingPrintStream:close:50]: Something tried to close the main output stream
[06:03:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: java.lang.Throwable
[06:03:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.common.TracingPrintStream.close(TracingPrintStream.java:51)
[06:03:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:443)
[06:03:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/sun.nio.cs.StreamEncoder.lockedClose(StreamEncoder.java:241)
[06:03:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/sun.nio.cs.StreamEncoder.close(StreamEncoder.java:226)
[06:03:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.io.OutputStreamWriter.close(OutputStreamWriter.java:267)
[06:03:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.io.BufferedWriter.implClose(BufferedWriter.java:398)
[06:03:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.io.BufferedWriter.close(BufferedWriter.java:380)
[06:03:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.io.PrintWriter.implClose(PrintWriter.java:448)
[06:03:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.io.PrintWriter.close(PrintWriter.java:440)
[06:03:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.apache.commons.compress.harmony.unpack200.Segment.unpackWrite(Segment.java:473)
[06:03:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.apache.commons.compress.harmony.unpack200.Segment.unpack(Segment.java:438)
[06:03:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.apache.commons.compress.harmony.unpack200.Archive.unpack(Archive.java:156)
[06:03:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.apache.commons.compress.harmony.unpack200.Pack200UnpackerAdapter.unpack(Pack200UnpackerAdapter.java:49)
[06:03:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.common.patcher.ClassPatchManager.setup(ClassPatchManager.java:157)
[06:03:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.common.asm.FMLSanityChecker.injectData(FMLSanityChecker.java:181)
[06:03:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:126)
[06:03:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:145)
[06:03:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
[06:03:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[06:03:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[06:03:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:37)
[06:03:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:11)
[06:03:09] [main/ERROR]: FML appears to be missing any signature data. This is not a good thing
[06:03:09] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[06:03:09] [main/INFO]: Injecting coremod FMLForgePlugin {net.minecraftforge.classloading.FMLForgePlugin} class transformers
[06:03:09] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
```

**Comment by Mr-Ao-Dragon** [comment]
我也遇到了，这种情况只能编辑Docker file自行构建没有run的版本

**Comment by Mr-Ao-Dragon** [comment]
@unitwk 请回复一下吧，有时候容器的启动命令确实不是必填的

**Comment by unitwk** [comment]
> @unitwk 请回复一下吧，有时候容器的启动命令确实不是必填的

确实可以不填启动命令，从而容器启动时会自动使用 dockerfile 中定义的启动命令。主要是我没时间去做这个功能升级，所以先放着吧。

**Comment by CMJNB** [comment]
> 我也遇到了，这种情况只能编辑Docker file自行构建没有run的版本

我也遇到了，请问一下具体怎么解决的？  @Mr-Ao-Dragon

**Comment by Mr-Ao-Dragon** [comment]
> > 我也遇到了，这种情况只能编辑Docker file自行构建没有run的版本
> 
> 我也遇到了，请问一下具体怎么解决的？  @Mr-Ao-Dragon 

自行构建Docker file，去掉run，然后贴不同的tag，push到自己Docker.io帐号
