### ISSUE TITLE
无法运行 UI 项目

### ISSUE THREAD

**Issue by BiDuang** [MCSManager/MCSManager#906]
**MCSManager Version**

在拉取 [UI项目](https://github.com/MCSManager/UI) 的最新版本（提交 716c8ba65e5e944271fedd45877b135a64a97043）后，安装依赖，尝试启动调试后出现报错：
```
yarn run v1.22.15
$ vue-cli-service serve
 ERROR  Error: Cannot find module '@babel/plugin-proposal-nullish-coalescing-operator'
Require stack:
- C:\Code\MCSManager-UI\node_modules\@babel\core\lib\config\files\plugins.js
- C:\Code\MCSManager-UI\node_modules\@babel\core\lib\config\files\index.js
- C:\Code\MCSManager-UI\node_modules\@babel\core\lib\index.js
- C:\Code\MCSManager-UI\node_modules\@vue\cli-plugin-babel\index.js
- C:\Code\MCSManager-UI\node_modules\@vue\cli-service\lib\Service.js
- C:\Code\MCSManager-UI\node_modules\@vue\cli-service\bin\vue-cli-service.js
- Did you mean "@babel/plugin-transform-nullish-coalescing-operator"?

Make sure that all the Babel plugins and presets you are using
are defined as dependencies or devDependencies in your package.json
file. It's possible that the missing plugin is loaded by a preset
you are using that forgot to add the plugin to its dependencies: you
can workaround this problem by explicitly adding the missing package
to your top-level package.json.

Error: Cannot find module '@babel/plugin-proposal-nullish-coalescing-operator'
Require stack:
- C:\Code\MCSManager-UI\node_modules\@babel\core\lib\config\files\plugins.js
- C:\Code\MCSManager-UI\node_modules\@babel\core\lib\config\files\index.js
- C:\Code\MCSManager-UI\node_modules\@babel\core\lib\index.js
- C:\Code\MCSManager-UI\node_modules\@vue\cli-plugin-babel\index.js
- C:\Code\MCSManager-UI\node_modules\@vue\cli-service\lib\Service.js
- C:\Code\MCSManager-UI\node_modules\@vue\cli-service\bin\vue-cli-service.js
- Did you mean "@babel/plugin-transform-nullish-coalescing-operator"?

Make sure that all the Babel plugins and presets you are using
are defined as dependencies or devDependencies in your package.json
file. It's possible that the missing plugin is loaded by a preset
you are using that forgot to add the plugin to its dependencies: you
can workaround this problem by explicitly adding the missing package
to your top-level package.json.

    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at resolve (node:internal/modules/cjs/helpers:108:19)
    at tryRequireResolve (C:\Code\MCSManager-UI\node_modules\@babel\core\lib\config\files\plugins.js:116:11)
    at resolveStandardizedNameForRequire (C:\Code\MCSManager-UI\node_modules\@babel\core\lib\config\files\plugins.js:150:19)
    at resolveStandardizedName (C:\Code\MCSManager-UI\node_modules\@babel\core\lib\config\files\plugins.js:165:12)
    at loadPlugin (C:\Code\MCSManager-UI\node_modules\@babel\core\lib\config\files\plugins.js:47:20)
    at loadPlugin.next (<anonymous>)
    at createDescriptor (C:\Code\MCSManager-UI\node_modules\@babel\core\lib\config\config-descriptors.js:139:16)
    at createDescriptor.next (<anonymous>)
    at evaluateSync (C:\Code\MCSManager-UI\node_modules\gensync\index.js:251:28)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

更换 npm 源，换用设备，换用 npm 与 yarn 都已确认对于此问题无效。

**System Info/Version**
- OS: Windows 10 22H2 19045.2846, Windows 11 22H2 22621.1555
**Node Version**
- Node: Nodejs v17.9.1

**Comment by huangsijun17** [comment]
UI项目只负责编译UI。运行请配合[前端项目](https://github.com/MCSManager/MCSManager-Web-Production)。

**Comment by BiDuang** [comment]
> UI项目只负责编译UI。运行请配合[前端项目](https://github.com/MCSManager/MCSManager-Web-Production)。

是，我需要基于fork上进行二次开发，而您提供的是成品。

**Comment by huangsijun17** [comment]
UI项目只负责 **编译UI** ，输出在`\public`。运行请 **配合** [前端项目](https://github.com/MCSManager/MCSManager-Web-Production)。

**Comment by BiDuang** [comment]
> UI项目只负责 **编译UI** ，输出在`\public`。运行请 **配合** [前端项目](https://github.com/MCSManager/MCSManager-Web-Production)。

很遗憾，编译也做不到，尝试编译结果如下：
```
yarn run v1.22.15
$ vue-cli-service build
 ERROR  Error: Cannot find module '@babel/plugin-proposal-nullish-coalescing-operator'
Require stack:
- C:\Code\MCSManager-UI\node_modules\@babel\core\lib\config\files\plugins.js
- C:\Code\MCSManager-UI\node_modules\@babel\core\lib\config\files\index.js
- C:\Code\MCSManager-UI\node_modules\@babel\core\lib\index.js
- C:\Code\MCSManager-UI\node_modules\@vue\cli-plugin-babel\index.js
- C:\Code\MCSManager-UI\node_modules\@vue\cli-service\lib\Service.js
- C:\Code\MCSManager-UI\node_modules\@vue\cli-service\bin\vue-cli-service.js
- Did you mean "@babel/plugin-transform-nullish-coalescing-operator"?

Make sure that all the Babel plugins and presets you are using
are defined as dependencies or devDependencies in your package.json
file. It's possible that the missing plugin is loaded by a preset
you are using that forgot to add the plugin to its dependencies: you
can workaround this problem by explicitly adding the missing package
to your top-level package.json.

Error: Cannot find module '@babel/plugin-proposal-nullish-coalescing-operator'
Require stack:
- C:\Code\MCSManager-UI\node_modules\@babel\core\lib\config\files\plugins.js
- C:\Code\MCSManager-UI\node_modules\@babel\core\lib\config\files\index.js
- C:\Code\MCSManager-UI\node_modules\@babel\core\lib\index.js
- C:\Code\MCSManager-UI\node_modules\@vue\cli-plugin-babel\index.js
- C:\Code\MCSManager-UI\node_modules\@vue\cli-service\lib\Service.js
- C:\Code\MCSManager-UI\node_modules\@vue\cli-service\bin\vue-cli-service.js
- Did you mean "@babel/plugin-transform-nullish-coalescing-operator"?

Make sure that all the Babel plugins and presets you are using
are defined as dependencies or devDependencies in your package.json
file. It's possible that the missing plugin is loaded by a preset
you are using that forgot to add the plugin to its dependencies: you
can workaround this problem by explicitly adding the missing package
to your top-level package.json.

    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at resolve (node:internal/modules/cjs/helpers:108:19)
    at tryRequireResolve (C:\Code\MCSManager-UI\node_modules\@babel\core\lib\config\files\plugins.js:116:11)
    at resolveStandardizedNameForRequire (C:\Code\MCSManager-UI\node_modules\@babel\core\lib\config\files\plugins.js:150:19)
    at resolveStandardizedName (C:\Code\MCSManager-UI\node_modules\@babel\core\lib\config\files\plugins.js:165:12)
    at loadPlugin (C:\Code\MCSManager-UI\node_modules\@babel\core\lib\config\files\plugins.js:47:20)
    at loadPlugin.next (<anonymous>)
    at createDescriptor (C:\Code\MCSManager-UI\node_modules\@babel\core\lib\config\config-descriptors.js:139:16)
    at createDescriptor.next (<anonymous>)
    at evaluateSync (C:\Code\MCSManager-UI\node_modules\gensync\index.js:251:28)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Bluemangoo** [comment]
1. 请核对yarn install是否正常；
2. 请核对package.json是否与云端同步（codespace会自动升级依赖版本）；
3. yarn出错的话请考虑npm（保留package-lock.json）；
4. npm安装还是出错就把lock文件删除再试；
5. 一直报错就yarn add那个缺少的包。

**Comment by unitwk** [comment]
我理解你遇到的问题，刚刚两名成员的回答都不属于正面回答你的问题。

我才用 npm i 重新尝试了一下，并未发现你遇到的问题。

另外，Github 的自动构建也很明确的告知了当前分支最新改动下是成功的（执行了 npm install 还执行了 npm run build），你提供的报错信息我从未遇到过，你可能只能自己解决。

https://github.com/MCSManager/UI/actions/runs/5241621104/jobs/9463961650

**Comment by unitwk** [comment]
以下是我本机尝试的输出：

```
PS C:\Users\Suwin> node -v
v18.16.0
PS C:\Users\Suwin> npm -v
9.5.1

PS D:\Workspace\MCSM\MCSManager-UI> npm i
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN old lockfile FetchError: Invalid response body while trying to fetch https://registry.npmjs.org/chokidar: Socket timeout
npm WARN old lockfile     at D:\SoftWare\Node\node_modules\npm\node_modules\minipass-fetch\lib\body.js:170:15
npm WARN old lockfile     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm WARN old lockfile     at async Response.json (D:\SoftWare\Node\node_modules\npm\node_modules\minipass-fetch\lib\body.js:75:17)
npm WARN old lockfile     at async RegistryFetcher.packument (D:\SoftWare\Node\node_modules\npm\node_modules\pacote\lib\registry.js:94:25)
npm WARN old lockfile     at async RegistryFetcher.manifest (D:\SoftWare\Node\node_modules\npm\node_modules\pacote\lib\registry.js:118:23)
npm WARN old lockfile     at async Array.<anonymous> (D:\SoftWare\Node\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:734:24)
npm WARN old lockfile  Could not fetch metadata for chokidar@3.5.2 FetchError: Invalid response body while trying to fetch https://registry.npmjs.org/chokidar: Socket timeout
npm WARN old lockfile     at D:\SoftWare\Node\node_modules\npm\node_modules\minipass-fetch\lib\body.js:170:15
npm WARN old lockfile     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm WARN old lockfile     at async Response.json (D:\SoftWare\Node\node_modules\npm\node_modules\minipass-fetch\lib\body.js:75:17)
npm WARN old lockfile     at async RegistryFetcher.packument (D:\SoftWare\Node\node_modules\npm\node_modules\pacote\lib\registry.js:94:25)
npm WARN old lockfile     at async RegistryFetcher.manifest (D:\SoftWare\Node\node_modules\npm\node_modules\pacote\lib\registry.js:118:23)
npm WARN old lockfile     at async Array.<anonymous> (D:\SoftWare\Node\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:734:24) {
npm WARN old lockfile   code: 'ERR_SOCKET_TIMEOUT',
npm WARN old lockfile   timeout: 15000,
npm WARN old lockfile   errno: 'ERR_SOCKET_TIMEOUT',
npm WARN old lockfile   type: 'system'
npm WARN old lockfile }
npm WARN old lockfile vue-loader-v16: No matching version found for vue-loader-v16@16.8.3.
npm WARN old lockfile     at module.exports (D:\SoftWare\Node\node_modules\npm\node_modules\npm-pick-manifest\lib\index.js:209:23)
npm WARN old lockfile     at RegistryFetcher.manifest (D:\SoftWare\Node\node_modules\npm\node_modules\pacote\lib\registry.js:119:22)
npm WARN old lockfile     at async Array.<anonymous> (D:\SoftWare\Node\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:734:24)
npm WARN old lockfile  Could not fetch metadata for vue-loader-v16@16.8.3 vue-loader-v16: No matching version found for vue-loader-v16@16.8.3.
npm WARN old lockfile     at module.exports (D:\SoftWare\Node\node_modules\npm\node_modules\npm-pick-manifest\lib\index.js:209:23)
npm WARN old lockfile     at RegistryFetcher.manifest (D:\SoftWare\Node\node_modules\npm\node_modules\pacote\lib\registry.js:119:22)
npm WARN old lockfile     at async Array.<anonymous> (D:\SoftWare\Node\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:734:24) {
npm WARN old lockfile   code: 'ETARGET',
npm WARN old lockfile   type: 'version',
npm WARN old lockfile   wanted: '16.8.3',
npm WARN old lockfile   versions: [
npm WARN old lockfile     '16.0.0-beta.5',
npm WARN old lockfile     '16.0.0-beta.5.1',
npm WARN old lockfile     '16.0.0-beta.5.2',
npm WARN old lockfile     '16.0.0-beta.5.3',
npm WARN old lockfile     '16.0.0-beta.5.4'
npm WARN old lockfile   ],
npm WARN old lockfile   distTags: { latest: '16.0.0-beta.5.4' },
npm WARN old lockfile   defaultTag: 'latest'
npm WARN old lockfile }

added 3 packages, and audited 1538 packages in 6m

124 packages are looking for funding
  run `npm fund` for details

37 vulnerabilities (1 low, 5 moderate, 22 high, 9 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

**Comment by BiDuang** [comment]
清除 npm 缓存后，再次尝试出现新的报错：

```
|  Building for production...Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (H:\WorkSpace\MCSM\MCSManager-UI\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (H:\WorkSpace\MCSM\MCSManager-UI\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (H:\WorkSpace\MCSM\MCSManager-UI\node_modules\webpack\lib\NormalModule.js:471:10)
    at H:\WorkSpace\MCSM\MCSManager-UI\node_modules\webpack\lib\NormalModule.js:503:5
    at H:\WorkSpace\MCSM\MCSManager-UI\node_modules\webpack\lib\NormalModule.js:358:12
    at H:\WorkSpace\MCSM\MCSManager-UI\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (H:\WorkSpace\MCSM\MCSManager-UI\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (H:\WorkSpace\MCSM\MCSManager-UI\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at H:\WorkSpace\MCSM\MCSManager-UI\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (H:\WorkSpace\MCSM\MCSManager-UI\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (H:\WorkSpace\MCSM\MCSManager-UI\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (H:\WorkSpace\MCSM\MCSManager-UI\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (H:\WorkSpace\MCSM\MCSManager-UI\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at H:\WorkSpace\MCSM\MCSManager-UI\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
|  Building for production...Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
                        throw e;
                        ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (H:\WorkSpace\MCSM\MCSManager-UI\node_modules\webpack\lib\util\createHash.js:135:53)
    at handleParseError (H:\WorkSpace\MCSM\MCSManager-UI\node_modules\webpack\lib\NormalModule.js:471:10)
    at H:\WorkSpace\MCSM\MCSManager-UI\node_modules\webpack\lib\NormalModule.js:503:5
    at H:\WorkSpace\MCSM\MCSManager-UI\node_modules\webpack\lib\NormalModule.js:358:12
    at H:\WorkSpace\MCSM\MCSManager-UI\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (H:\WorkSpace\MCSM\MCSManager-UI\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (H:\WorkSpace\MCSM\MCSManager-UI\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at H:\WorkSpace\MCSM\MCSManager-UI\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at context.callback (H:\WorkSpace\MCSM\MCSManager-UI\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at H:\WorkSpace\MCSM\MCSManager-UI\node_modules\cache-loader\dist\index.js:147:7
    at H:\WorkSpace\MCSM\MCSManager-UI\node_modules\graceful-fs\graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:197:23) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

经过检查后发现需要在 `package.json` 预先指定环境变量才能正确启动。（Node 17+特性）
参阅 https://stackoverflow.com/questions/69962209/what-is-openssl-legacy-provider-in-node-js-v17

**Comment by Bluemangoo** [comment]
不应该啊我用的是18没这个问题。

**Comment by BiDuang** [comment]
> 不应该啊我用的是18没这个问题。

不清楚，在 Windows 上全新安装的 Node 18.16.0 会有以上问题

**Comment by Bluemangoo** [comment]
你确定你依赖能正常安装？

https://pastes.dev/3huCHX7DXY

**Comment by Bluemangoo** [comment]
我重新装了环境，成功复现。

[All logs](https://pastes.dev/xuOR5XSUpu)

**Comment by Bluemangoo** [comment]
> 我理解你遇到的问题，刚刚两名成员的回答都没有正面回答你的问题。
> 
> 我才用 npm i 重新尝试了一下，并未发现你遇到的问题。
> 
> 另外，Github 的自动构建也很明确的告知了当前分支最新改动下是成功的（执行了 npm install 还执行了 npm run build），你提供的报错信息我从未遇到过，你可能只能自己解决。
> 
> https://github.com/MCSManager/UI/actions/runs/5241621104/jobs/9463961650

Actions使用的环境是16.x。

[workflow \(Highlighted\)](https://github.com/MCSManager/UI/blob/716c8ba65e5e944271fedd45877b135a64a97043/.github/workflows/webpack.yml#LL15C23-L15C35)

**Comment by Bluemangoo** [comment]
@unitwk 是否考虑升级依赖版本

```text
PS C:\Users\chenx\Desktop\TempFolder\UI> ncu
Checking C:\Users\chenx\Desktop\TempFolder\UI\package.json
[====================] 31/31 100%

 @vue/cli-plugin-babel           ~4.5.0  →   ~5.0.8
 @vue/cli-plugin-eslint          ~4.5.0  →   ~5.0.8
 @vue/cli-plugin-router         ^4.5.13  →   ^5.0.8
 @vue/cli-service                ~4.5.0  →   ~5.0.8
 @vue/compiler-sfc               ^3.0.0  →   ^3.3.4
 axios                          ^0.21.2  →   ^1.4.0
 core-js                         ^3.6.5  →  ^3.31.0
 echarts                         ^5.2.2  →   ^5.4.2
 element-plus            ^1.1.0-beta.15  →   ^2.3.6
 eslint                          ^6.7.2  →  ^8.43.0
 eslint-plugin-vue               ^7.0.0  →  ^9.14.1
 prettier                        ^2.3.2  →   ^2.8.8
 sass                           ^1.27.0  →  ^1.63.4
 sass-loader                    ^10.0.4  →  ^13.3.2
 socket.io                       ^4.5.3  →   ^4.6.2
 socket.io-client                ^4.1.2  →   ^4.6.2
 vue                             ^3.2.9  →   ^3.3.4
 vue-i18n                       ^9.1.10  →   ^9.2.2
 vue-router                    ^4.0.0-0  →   ^4.2.2
 vuex                            ^4.0.2  →   ^4.1.0
 workbox-webpack-plugin          ^6.5.4  →   ^7.0.0
 xterm                          ^4.12.0  →   ^5.2.1
 xterm-addon-fit                 ^0.5.0  →   ^0.7.0
 xterm-addon-web-links           ^0.4.0  →   ^0.8.0

Run ncu -u to upgrade package.json
```

**Comment by BiDuang** [comment]
> 我重新装了环境，成功复现。
> 
> [All logs](https://pastes.dev/xuOR5XSUpu)

可以通过指定环境变量来解决
[#101](https://github.com/MCSManager/UI/pull/101)

**Comment by Bluemangoo** [comment]
尝试后发现，更新依赖不行，，，只能指定环境变量了。

**Comment by huangsijun17** [comment]
openssl v3的兼容问题？建议看这篇文章：
[Node.js Web 项目报错 error:0308010C:digital envelope routines::unsupported 的解决方案 - XiaoJin233 - 简书](https://www.jianshu.com/p/edbad6875b7e)

**Comment by Bluemangoo** [comment]
> openssl v3的兼容问题？建议看这篇文章： [Node.js Web 项目报错 error:0308010C:digital envelope routines::unsupported 的解决方案 - XiaoJin233 - 简书](https://www.jianshu.com/p/edbad6875b7e)

本文方法试过了没用。

**Comment by Bluemangoo** [comment]
升级依赖需要同时更新代码，工作量不小，有空的可以搞搞。

**Comment by unitwk** [comment]
不能依赖库，否则UI仓库要重做很多地方，很多依赖库的升级都是破坏性升级的。

**Comment by Bluemangoo** [comment]
我检查了一下，dev dependencies里面其它没问题，vue-cli相关不行。vue-cli升级到5.0.0+语法会有相关调整，比如说有些地方的v-model不能使用。如果有人做倒是可以试试。这个问题出在webpack，vue-cli的依赖。手动装新版本没有用（试过了）。但是目前合并的pr只能算是紧急措施，安全性不够的。node17+换ssl库的目的就是为了安全性。迟早该放弃旧版本依赖的。

@unitwk

**Comment by unitwk** [comment]
> 我检查了一下，dev dependencies里面其它没问题，vue-cli相关不行。vue-cli升级到5.0.0+语法会有相关调整，比如说有些地方的v-model不能使用。如果有人做倒是可以试试。这个问题出在webpack，vue-cli的依赖。手动装新版本没有用（试过了）。但是目前合并的pr只能算是紧急措施，安全性不够的。node17+换ssl库的目的就是为了安全性。迟早该放弃旧版本依赖的。
> 
> @unitwk

前端项目开发工具不需要安全性，不用杞人忧天。

Webpack 和 Vue CLI 等相关工具链一年能产出几十个高危漏洞，如果跟随最新版本的脚步前进，那么工作量将是成本的上升。
